---
before_install:
  - cd ./PurBeurre
  - export PYTHONPATH="$(pwd)"
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - export CHROME_BIN=chromium-browser

language: python

python:
  - "3.6"

addons:
  chrome: stable
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

services:
  - postgresql

before_script:
  - pip3 install -r requirements.txt
  - psql -c "create database purbeurre;" -U postgres

script:
  - python manage.py fill_db
  - python manage.py test

# safelist
branches:
  only:
    - newP10
