---
before_install:
  - cd ./PurBeurre
  - export PYTHONPATH="$(pwd)"
  - chmod +x manage.py
  - wget https://chromedriver.storage.googleapis.com/84.0.4147.30/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d ~/
  - export CHROME_BIN=chromium-browser

language: python

python:
  - "3.6"

addons:
  chrome: stable
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12

services:
  - postgresql

env:
  global:
    - DJANGO_SETTINGS_MODULE="PurBeurre.settings"
    - PGPORT=5433

before_script:
  - pip3 install -r requirements.txt
  - psql -c "CREATE ROLE root SUPERUSER LOGIN CREATEDB";
  - psql -c "CREATE DATABASE purbeurre WITH OWNER = root ENCODING = 'UTF8' CONNECTION LIMIT = -1;"


script:
  - python manage.py test

# safelist
branches:
  only:
    - newP10
